import Controller.AddStudentController
import Model.Student
import javafx.application.Application
import javafx.geometry.Insets
import javafx.scene.Scene
import javafx.scene.control.Button
import javafx.scene.control.Label
import javafx.scene.control.TextField
import javafx.scene.layout.GridPane
import javafx.stage.Stage

class AddStudentWindow : Application() {
    private val addStudentController = AddStudentController(this)

    override fun start(primaryStage: Stage) {
        primaryStage.title = "Add Student"

        val grid = GridPane()
        grid.padding = Insets(10.0)
        grid.hgap = 10.0
        grid.vgap = 10.0

        val lastNameLabel = Label("Last Name:")
        val lastNameField = TextField()
        grid.add(lastNameLabel, 0, 0)
        grid.add(lastNameField, 1, 0)

        val firstNameLabel = Label("First Name:")
        val firstNameField = TextField()
        grid.add(firstNameLabel, 0, 1)
        grid.add(firstNameField, 1, 1)

        val middleNameLabel = Label("Middle Name:")
        val middleNameField = TextField()
        grid.add(middleNameLabel, 0, 2)
        grid.add(middleNameField, 1, 2)

        val phoneLabel = Label("Phone:")
        val phoneField = TextField()
        grid.add(phoneLabel, 0, 3)
        grid.add(phoneField, 1, 3)

        val telegramLabel = Label("Telegram:")
        val telegramField = TextField()
        grid.add(telegramLabel, 0, 4)
        grid.add(telegramField, 1, 4)

        val emailLabel = Label("Email:")
        val emailField = TextField()
        grid.add(emailLabel, 0, 5)
        grid.add(emailField, 1, 5)

        val githubLabel = Label("GitHub:")
        val githubField = TextField()
        grid.add(githubLabel, 0, 6)
        grid.add(githubField, 1, 6)

        val addButton = Button("Add Student")
        grid.add(addButton, 1, 7)

        addButton.setOnAction {
            val student = Student(
                id = 0, // ID will be generated by the database
                lastName = lastNameField.text,
                firstName = firstNameField.text,
                middleName = middleNameField.text,
                phone = phoneField.text,
                telegram = telegramField.text,
                email = emailField.text,
                github = githubField.text
            )
            println("Student added: $student")
        }

        val scene = Scene(grid, 400.0, 400.0)
        primaryStage.scene = scene
        primaryStage.show()
    }
}